#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x71C636695B147849 (dict-upload@aspell.net)
#
Name     : aspell-es
Version  : 1.11.2
Release  : 1
URL      : http://mirrors.kernel.org/gnu/aspell/dict/es/aspell6-es-1.11-2.tar.bz2
Source0  : http://mirrors.kernel.org/gnu/aspell/dict/es/aspell6-es-1.11-2.tar.bz2
Source1 : http://mirrors.kernel.org/gnu/aspell/dict/es/aspell6-es-1.11-2.tar.bz2.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: aspell-es-license = %{version}-%{release}
BuildRequires : aspell
Patch1: 0001-configure-ignore-unknown-options.patch

%description
GNU Aspell 0.60 Spanish (Español) Dictionary Package
Version 1.11-2
2010-11-22
Aspell Dictionary Maintained By:
Agustin Martin Domingo <agustin martin at hispalinux es>
Original Word List Maintained By:
Santiago Rodríguez <srodri at fi upm es>
Jesus Carretero <jesus carretero at uc3m es>
Wordlist URL: http://www.datsi.fi.upm.es/~coes/
Source Version: 1.11-2
This word list is considered accurate.

%package license
Summary: license components for the aspell-es package.
Group: Default

%description license
license components for the aspell-es package.


%prep
%setup -q -n aspell6-es-1.11-2
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568740050
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1568740050
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/aspell-es
cp COPYING %{buildroot}/usr/share/package-licenses/aspell-es/COPYING
cp Copyright %{buildroot}/usr/share/package-licenses/aspell-es/Copyright
%make_install

%files
%defattr(-,root,root,-)
/usr/lib64/aspell-0.60/castellano.alias
/usr/lib64/aspell-0.60/es.dat
/usr/lib64/aspell-0.60/es.multi
/usr/lib64/aspell-0.60/es.rws
/usr/lib64/aspell-0.60/es_affix.dat
/usr/lib64/aspell-0.60/espanol.alias
/usr/lib64/aspell-0.60/spanish.alias

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/aspell-es/COPYING
/usr/share/package-licenses/aspell-es/Copyright
